import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const Env = createEnv({
  server: {
    SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
    DATABASE_URL: z.string().optional(),
    LOGTAIL_SOURCE_TOKEN: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().optional(),
    STRIPE_WEBHOOK_SECRET: z.string().optional(),
    BILLING_PLAN_ENV: z.enum(['dev', 'test', 'prod']).optional(),
    RUNPOD_API_KEY: z.string().optional(),
    RUNPOD_ENDPOINT_ID: z.string().optional(),
    CF_API_TOKEN: z.string().optional(),
    CLOUDFLARE_ACCOUNT_ID: z.string().optional(),
    CLOUDFLARE_R2_ACCESS_KEY_ID: z.string().optional(),
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: z.string().optional(),
    CLOUDFLARE_R2_BUCKET: z.string().optional(),
    CLOUDFLARE_R2_PUBLIC_BASE_URL: z.string().optional(),
    JWT_SECRET: z.string().optional(),
    WEBHOOK_SECRET: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().optional(),
    NEXT_PUBLIC_SUPABASE_URL: z.string().optional(),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().optional(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().optional(),
    NEXT_PUBLIC_BASE_URL: z.string().optional(),
    NEXT_PUBLIC_SITE_URL: z.string().optional(),
  },
  shared: {
    NODE_ENV: z.enum(['test', 'development', 'production']).optional(),
  },
  runtimeEnv: {
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    DATABASE_URL: process.env.DATABASE_URL,
    LOGTAIL_SOURCE_TOKEN: process.env.LOGTAIL_SOURCE_TOKEN,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    BILLING_PLAN_ENV: process.env.BILLING_PLAN_ENV,
    RUNPOD_API_KEY: process.env.RUNPOD_API_KEY,
    RUNPOD_ENDPOINT_ID: process.env.RUNPOD_ENDPOINT_ID,
    CF_API_TOKEN: process.env.CF_API_TOKEN,
    CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
    CLOUDFLARE_R2_ACCESS_KEY_ID: process.env.CLOUDFLARE_R2_ACCESS_KEY_ID,
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY,
    CLOUDFLARE_R2_BUCKET: process.env.CLOUDFLARE_R2_BUCKET,
    CLOUDFLARE_R2_PUBLIC_BASE_URL: process.env.CLOUDFLARE_R2_PUBLIC_BASE_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    WEBHOOK_SECRET: process.env.WEBHOOK_SECRET,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NODE_ENV: process.env.NODE_ENV,
  },
  skipValidation: process.env.NODE_ENV === 'development',
});

export const ENV_CLIENT = {
  SUPABASE_URL: Env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_ANON_KEY: Env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  APP_URL: Env.NEXT_PUBLIC_APP_URL || 'https://app.alphogen.com',
  SITE_URL: Env.NEXT_PUBLIC_SITE_URL || 'https://app.alphogen.com',
  BASE_URL: Env.NEXT_PUBLIC_BASE_URL || 'https://app.alphogen.com',
};

export const ENV_SERVER = {
  SUPABASE_SERVICE_ROLE_KEY: Env.SUPABASE_SERVICE_ROLE_KEY,
  WEBHOOK_SECRET: Env.WEBHOOK_SECRET,
  RUNPOD_API_KEY: Env.RUNPOD_API_KEY,
  RUNPOD_ENDPOINT_ID: Env.RUNPOD_ENDPOINT_ID,
  CLOUDFLARE_ACCOUNT_ID: Env.CLOUDFLARE_ACCOUNT_ID,
  CLOUDFLARE_R2_ACCESS_KEY_ID: Env.CLOUDFLARE_R2_ACCESS_KEY_ID,
  CLOUDFLARE_R2_SECRET_ACCESS_KEY: Env.CLOUDFLARE_R2_SECRET_ACCESS_KEY,
  CLOUDFLARE_R2_BUCKET: Env.CLOUDFLARE_R2_BUCKET,
  CLOUDFLARE_R2_PUBLIC_BASE_URL: Env.CLOUDFLARE_R2_PUBLIC_BASE_URL,
  DATABASE_URL: Env.DATABASE_URL,
  LOGTAIL_SOURCE_TOKEN: Env.LOGTAIL_SOURCE_TOKEN,
};
