name = "alphogenai-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.prod]
name = "alphogenai-worker"
routes = [
  { pattern = "api.alphogen.com/*", zone_id = "824fa72287d21dd30f97f188f650d6b7" }
]

[[env.prod.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "alphogenai-assets"

[env.dev]
name = "alphogenai-worker-dev"

[[env.dev.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "alphogenai-assets-dev"
