name = "alphogenai-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"
account_id = "a3ac983a6a5ce4bb150638e1f620c2a7"  # remplace par ton vrai ID
workers_dev = true

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "alphogenai-assets"         # ton bucket R2 existant
