name = "alphogenai-worker"
main = "src/index.ts"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]
account_id = "a3ac983a6a5ce4bb150638e1f620c2a7"

# Les secrets (APP_ADMIN_TOKEN, etc.) restent gérés dans le Dashboard CF.
# Ne rien dupliquer ici.
