name = "alphogenai-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"
workers_dev = true
# Si tu vois plus tard des erreurs "process"/"Buffer", dé-commente la ligne suivante :
# compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "alphogenai-assets"
