name = "alphogenai-worker"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# On lit l'account_id depuis la variable GitHub (CI)
account_id = "${CF_ACCOUNT_ID}"

[observability]
enabled = true

[vars]
# Vos variables runtime si nécessaire (exposées côté worker)
