name: pulumi-clean

on:
  workflow_dispatch:
    inputs:
      stack:
        description: "Stack à nettoyer (staging ou prod)"
        required: true
        default: "staging"

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install infra deps (Node)
        working-directory: infra
        run: npm ci || npm i

      # 👉 Pose les configs de stack AVANT refresh/up
      - name: Ensure Pulumi config (stack)
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          set -e
          pulumi stack select "${{ github.event.inputs.stack }}" || pulumi stack init "${{ github.event.inputs.stack }}"
          pulumi config set cfAccountId    "${{ vars.CF_ACCOUNT_ID }}"     --stack "${{ github.event.inputs.stack }}"
          pulumi config set cfDnsZone      "${{ vars.CF_DNS_ZONE }}"       --stack "${{ github.event.inputs.stack }}"
          pulumi config set cfWorkerName   "${{ vars.CF_WORKER_NAME }}"    --stack "${{ github.event.inputs.stack }}"

      - name: Pulumi state cleanup
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          set -e
          pulumi stack select "${{ github.event.inputs.stack }}"

          echo "=== Etat AVANT ==="
          pulumi state ls || true

          echo "=== Supprime d'anciens PagesProject suivis (on ne les gère plus via Pulumi) ==="
          pulumi state ls --json | jq -r '.[] | select(.type=="cloudflare:index/pagesProject:PagesProject") | .urn' \
            | xargs -r -n1 pulumi state delete -y

          echo "=== Supprime d'éventuelles routes orphelines dans le state ==="
          pulumi state ls --json | jq -r '.[] | select(.type=="cloudflare:index/workerRoute:WorkerRoute") | .urn' \
            | xargs -r -n1 pulumi state delete -y

          echo "=== Refresh ==="
          pulumi refresh -y

          echo "=== Re-create selon le code actuel ==="
          pulumi up -y

          echo "=== Etat APRES ==="
          pulumi state ls
